project:
  type: book
  pre-render: R/setup.R

callout-appearance: simple
# see this quarto discussion issue for info on lua filter
# https://github.com/quarto-dev/quarto-cli/discussions/2869#discussioncomment-3886253
filters: 
 - chapters/lua/callouts.lua

execute:
  freeze: auto  
  echo: true 
  dev: "ragg_png"
  dpi: 740 
  out.width: "80%"
  fig.width: 6
  fig.asp: 0.618
  fig.retina: 3
  fig.align: "center"
  fig.show: "hold"
  
book:
  title: "Causal Inference in R"
  author: ["Malcolm Barrett", "Lucy D'Agostino McGowan", "Travis Gerke"]
  date: "today"
  repo-url: https://github.com/malcolmbarrett/causal-inference-in-r
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    
    - part: Asking Causal Questions
      chapters: 
      - chapters/chapter-01.qmd
      - chapters/chapter-02.qmd
      - chapters/chapter-03.qmd
      - chapters/chapter-04.qmd
      - chapters/chapter-05.qmd
      
    - part: The Design Phase 
      chapters: 
      - chapters/chapter-06.qmd
      - chapters/chapter-07.qmd
      - chapters/chapter-08.qmd
      - chapters/chapter-09.qmd
      
    - part: Estimating Causal Effects 
      chapters: 
      - chapters/chapter-10.qmd
      - chapters/chapter-11.qmd
      - chapters/chapter-12.qmd
      - chapters/chapter-13.qmd
      - chapters/chapter-14.qmd
      - chapters/chapter-15.qmd
      - chapters/chapter-16.qmd
      - chapters/chapter-17.qmd
      - chapters/chapter-18.qmd
      - chapters/chapter-19.qmd
      
    - chapters/references-99.qmd
      
bibliography: citations.bib

format:
  html:
    code-link: true
    tbl-cap-location: bottom
    theme:
      - cosmo
      - style.scss
    include-in-header: "plausible.html"
  #pdf:
    #tbl-cap-location: bottom
    #documentclass: krantz
    #link-citations: true
    #colorlinks: true
    #lot: true
    #lof: true
    #includes:
    #  in_header: latex/preamble.tex
    #  before_body: latex/before_body.tex
    #  after_body: latex/after_body.tex

editor_options:
  markdown:
    wrap: sentence
    canonical: true
    
